second_Edition/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 用户
    url(r'^users/', include('users.urls', namespace='users')),
    # 首页（公共）
    url(r'^', include('commons.urls', namespace='commons')),
    # 首页（公共）
    url(r'^work/', include('work.urls', namespace='work')),
]

users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # 登录页面
    url(r'^$', views.user_login, name='sign_in'),
    url(r'^login/$', views.user_login, name='sign_in'),
    # 注册页面
    url(r'^register/$', views.register, name='register'),
    # 验证码
    url(r'^code/$', views.code, name='code'),
    # 验证邮箱是否可用
    url(r'^(.*)/checkemail/$', views.checkemail, name='checkemail'),
    # 验证昵称
    url(r'^(.*)/checkusername/$', views.checkusername, name='checkusername'),
    # 注册后提示
    url(r'^tips/$', views.tips, name='tips'),
    # 邮箱验证
    url(r'^email_verification/(?P<token>.*)$', views.email_verification, name='email_verification'),
    # 验证码验证
    url(r'^(\w+)/checkcode/$', views.checkcode, name='checkcode'),
    # 退出登录
    url(r'^user_logout/$', views.user_logout, name='user_logout'),
    # 个人主页
    url(r'^(\d+)/user_info/$', views.user_info, name='user_info'),
    # ajax验证旧密码
    url(r'^(\w+)/check_password/$', views.check_password, name='check_password'),
    # 修改密码
    url(r'change_pwd/', views.change_pwd, name='change_pwd'),
    # 修改昵称
    url(r'(\w+)/change_username/', views.change_username, name='change_username'),
    # 修改邮箱
    url(r'change_email/', views.change_email, name='change_email'),
]

work/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index/$', views.index, name='index'),
    url(r'^file_update/$', views.file_update, name='file_update'),
    url(r'^update/$', views.update, name='update'),
    url(r'^file_info/$', views.file_info, name='file_info'),
    url(r'^trans_type/$', views.trans_type, name='trans_type'),
    # url(r'^(\d+)/(\d+)/(\d+)/work_wait/$', views.work_wait, name='work_wait'),
    url(r'^work_wait/$', views.work_wait, name='work_wait'),
    # 工作区
    # 中文编译界面
    url(r'^(\d+)/work/$', views.work, name='work'),
    # 英文编译界面
    url(r'^(\d+)/enwork/$', views.enwork, name='enwork'),
    # 下载/导出  word
    url(r'^(\d+)/downloads/$', views.downloads, name='downloads'),
    # 删除文档项目
    url(r'^(\d+)/del_file/$', views.del_file, name='del_file'),
    # 单行/全部修改译文
    url(r'^(\d+)/([\s\S]*)/change_yiwen/$', views.change_yiwen, name='change_yiwen'),
    # url(r'^(\d+)/enchange_yiwen/$', views.enchange_yiwen, name='enchange_yiwen'),
    # 生成word
    # url(r'^(\d+)/word_ok/$', views.word_ok, name='word_ok'),
    # 搜索原文
    url(r'serch_yuanwen/(\d+)/$', views.serch_yuanwen, name="serch_yuanwen"),
    url(r'serch_yiwen/(\d+)/$', views.serch_yiwen, name="serch_yiwen"),
    # 中文
    url(r'bdjson/([\s\S]*)/(\d+)/$', views.bdjson, name="bdjson"),
    url(r'sgjson/([\s\S]*)/(\d+)/$', views.sgjson, name="sgjson"),
    # 英文
    url(r'en_baidu/([\s\S]*)/(\d+)/$', views.en_baidu, name="en_baidu"),
    url(r'ensgjson/([\s\S]*)/(\d+)/$', views.ensgjson, name="ensgjson"),
    # url(r'all_change_yiwen/(\d+)/([\s\S]*)/$', views.all_change_yiwen, name="all_change_yiwen"),
    url(r'all_save_yiwen/(\d+)/([\s\S]*)/$', views.all_save_yiwen, name="all_save_yiwen"),
    url(r'change_befor/(\d+)/$', views.change_befor, name="change_befor"),
    url(r'change_old/(\d+)/$', views.change_old, name="change_old"),
    url(r'change_content/([\s\S]*)/(\d+)/$', views.change_content, name="change_content"),
    url(r'en_content_change/([\s\S]*)/(\d+)/$', views.en_content_change, name="en_content_change"),
    url(r'yuanwen_check/(\d+)/$', views.yuanwen_check, name="yuanwen_check"),
    url(r'yiwen_check/(\d+)/$', views.yiwen_check, name="yiwen_check"),
    # 中文编译
    url(r'zh_rs/(\d+)/$', views.zh_rs, name="zh_rs"),
    url(r'en_read_save/(\d+)/$', views.en_read_save, name="en_read_save"),
]

work/models.py
from django.db import models
from django.contrib.auth.models import User


class file_information(models.Model):
    id = models.AutoField(primary_key=True)
    file_name = models.CharField(verbose_name="文件名称", max_length=526)
    file_info = models.TextField(verbose_name="文件备注")
    file_create_time = models.DateTimeField(auto_now_add=True, verbose_name="文件创建时间")
    file_change_time = models.DateTimeField(auto_now=True, verbose_name="文件修改时间")
    file = models.FileField(upload_to="static/work/doc/", verbose_name="文件")
    # 文件处理状态  # 1：进行中   0：已完成   2：删除
    file_status = models.IntegerField(default=1, verbose_name="当前状态")
    over_time = models.CharField(default="", max_length=255, verbose_name="截至时间")
    # html_path = models.CharField(default="", max_length=256, verbose_name="html文件")
    word_path = models.CharField(default="", max_length=256, verbose_name="导出word文件")
    # 翻译种类 1：百度翻译       2：搜狗翻译
    fanyi_zl = models.IntegerField(default=0, verbose_name="翻译种类")
    # 翻译种类 1：中文翻译       2：英文翻译
    # fanyi_fx = models.IntegerField(default=0, verbose_name="翻译方向")
    # 1 中译英 2 英译中 0 未设置
    yuan = models.IntegerField(default=0, verbose_name="源文语言种类")
    # 2 中译英 1 英译中 0 未设置
    mubiao = models.IntegerField(default=0, verbose_name="目标语言种类")
    # 文章总字数
    all_num = models.IntegerField(default=0, verbose_name="文章总字数")
    # 当前已修改的字数
    numing = models.IntegerField(default=0, verbose_name="已修改的字数")
    # 文章总段数
    all_para = models.IntegerField(default=0, verbose_name="文章总段数")
    # 当前已修改的段落数
    paraing = models.IntegerField(default=0, verbose_name="已修改段数")
    # 当前进度 保留整数
    jindu = models.IntegerField(default=0, verbose_name="当前的进度")
    # 关联用户
    file_user = models.ForeignKey(User, models.CASCADE)


class yuanwen(models.Model):
    id = models.AutoField(primary_key=True)
    yuanwen = models.TextField(verbose_name="原文句子")
    yuanwen_change = models.TextField(verbose_name="原文修改句子", default="")
    yuanwen_style = models.CharField(max_length=256, verbose_name="原文标题样式", default="")
    style_value = models.CharField(max_length=255, verbose_name="样式的值", default="")
    # 是否修改过 默认0 未修改过  1 修改过  不可再次修改
    check_changeed = models.IntegerField(default=0, verbose_name="是否修改过")
    # gl = models.OneToOneField('self', null=True, blank=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, models.CASCADE)
    file = models.ForeignKey(file_information, models.CASCADE)


class yiwen(models.Model):
    id = models.AutoField(primary_key=True)
    yiwen = models.TextField(verbose_name="译文句子")
    yiwen_change = models.TextField(verbose_name="译文修改句子", default=" ")
    yiwen_wait_over = models.TextField(verbose_name="译文待人工编译", default="")
    yiwen_style = models.CharField(max_length=256, verbose_name="译文标题样式", default="")
    style_value = models.CharField(max_length=255, verbose_name="样式的值", default="")
    gl = models.OneToOneField(yuanwen, on_delete=models.CASCADE)
    user = models.ForeignKey(User, models.CASCADE)
    file = models.ForeignKey(file_information, models.CASCADE)

work/views.py
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, StreamingHttpResponse, response
# 登录检查
from django.contrib.auth.decorators import login_required
# 限制访问方式
from django.views.decorators.http import require_http_methods
# 引入数据库
from . import models
# 引入事务
from django.db import transaction
# 引入用户
from . import task
import docx
from .task import fanyi, enfanyi, fanyi_save, en_fanyi_save, Sogou
import random
import subprocess



# 首页面
@login_required
def index(request):
    files = models.file_information.objects.filter(file_user=request.user)
    return render(request, 'work/index.html', {"files":files})


# 上传首页面
@login_required
def update(request):
    return render(request, 'work/update.html', {})


# 文件上传
@login_required
@require_http_methods(["POST"])
def file_update(request):
    # try:
    print("开始获取")
    # 获取文件和名称
    file = request.FILES.get('file')
    name = file.name
    # 获取当前的用户
    user = request.user
    print("获取到，存储")
    print(file, name, user)
    # 存入数据库
    update_file = models.file_information(file_name = name, file=file, file_user=user)
    print("???")
    print(update_file)
    update_file.save()
    # 根据文件位置进行修改
    doc_path = "/home/admin/second_Edition/" + str(update_file.file)
    print(doc_path)
    id = update_file.id
    if doc_path.split('.', -1)[-1] == "doc":
        print("不是docx")
        a = subprocess.check_output(["soffice", "--headless",
                                     "--invisible", "--convert-to",
                                     "docx", doc_path,
                                     "--outdir", "/home/admin/second_Edition/static/work/doc"])
        name = str(update_file.file) + "x"
        print("docx" + name)
        print(a)
        print(name)
        docx_save = models.file_information.objects.get(pk=id)
        docx_save.file = name
        docx_save.save()
    print("end")

    return render(request, 'work/file_info.html', {"msg": file.name, 'id': update_file.id})
    # except:
    #     return render(request, 'work/file_info.html', {"msg": "cuowu "})


# 文件信息填写
@login_required
@require_http_methods(["POST"])
def file_info(request):
    name = request.POST['name']
    info = request.POST['info']
    over_time = request.POST['over_time']
    id = request.POST['id']     # 文件ID
    print(id)
    yuan = request.POST['yuan']
    print("源："+yuan)
    mubiao = request.POST['mubiao']
    print("目标："+ mubiao)
    print("时间", over_time)
    # 查询当前的数据
    file = models.file_information.objects.get(pk=id)
    file.file_name = name
    file.file_info = info
    file.yuan = yuan
    file.mubiao = mubiao
    file.over_time = over_time
    file.save()
    print("保存完成")
    return render(request, 'work/trans_type.html', {'id': id})


# 选择翻译种类
@login_required
@require_http_methods(["POST"])
def trans_type(request):
    id = request.POST['id']
    zl = request.POST['zl']
    print("翻译的种类"+zl)
    file = models.file_information.objects.get(pk=id)
    file.fanyi_zl= zl
    file.save()
    print(file)
    fx = file.mubiao
    print("fx", fx)
    # zl = file.fanyi_zl
    # print("zl:",zl)
    if fx == 2:
        print("等于1")
        return render(request, 'work/work_wait.html', {"file":file})
    if fx == 1:
        print("等于2")
        return render(request, 'work/work_enwait.html', {"file":file})


@login_required
# @require_http_methods(["POST"])
# def work_wait(request, id, fx, yuan):
def work_wait(request):
    return render(request, 'work/work_wait.html', {})


# 中文编译界面
@login_required
def work(request, file_id):
    file = models.file_information.objects.get(pk = file_id)
    print(file.file_name)
    # 获取当前的用户
    user = request.user
    # 获取当前ID的用户
    id_user = file.file_user
    # 判断是否用户是否为一人
    if user == id_user:
        yuanwen = models.yuanwen.objects.filter(file = file_id)
        print(len(yuanwen))
        print(yuanwen)
        if len(yuanwen) > 1:
            yiwen = models.yiwen.objects.filter(file = file_id)
            file = models.file_information.objects.get(pk = file_id)
            wenjian = zip(yuanwen, yiwen)
            return render(request, 'work/work.html', {"wenjian": wenjian, "file_id": file_id, "filename":file.file_name, "file":file})
        else:
            path = file.file
            path = str(path)
            task.zh_rs(path, request.user, file, file.mubiao)
            return redirect("/work/" + file_id + "/work/")
    else:
        return render(request, 'work/work_error.html', {})


# 英文编译界面
@login_required
def enwork(request, file_id):
    file = models.file_information.objects.get(pk=file_id)
    print(file.file_name)
    # 获取当前的用户
    user = request.user
    # 获取当前ID的用户
    id_user = file.file_user
    # 判断是否用户是否为一人
    if user == id_user:
        yuanwen = models.yuanwen.objects.filter(file=file_id)
        print(len(yuanwen))
        print(yuanwen)
        if len(yuanwen) > 1:
            yiwen = models.yiwen.objects.filter(file=file_id)
            file = models.file_information.objects.get(pk=file_id)
            wenjian = zip(yuanwen, yiwen)
            return render(request, 'work/enwork.html',
                          {"wenjian": wenjian, "file_id": file_id, "filename": file.file_name, "file": file})
        else:
            path = file.file
            path = str(path)
            task.en_read_save(path, request.user, file, file.mubiao)
            return redirect("/work/" + file_id + "/work/")
    else:
        return render(request, 'work/work_error.html', {})


import re
# 将获取到的16进制颜色转化为rgb颜色
def toRgb(tmp):
    opt = re.findall(r'(.{2})', tmp)  # 将字符串两两分割
    strs = ""  # 用以存放最后结果
    for i in range(0, len(opt)):  # for循环，遍历分割后的字符串列表
        strs += str(int(opt[i], 16)) + ","  # 将结果拼接成12，12，12格式
    return strs[0:-1]


from docx.shared import RGBColor


def word_ok(file_id):
    file = models.file_information.objects.get(pk = file_id)
    print("word名称：", file.file_name)
    document = docx.Document()
    yiwen = models.yiwen.objects.filter(file = file)
    for y in yiwen:
        print("1"+y.yiwen_wait_over)
        print("2"+y.yiwen_style)
        print("3"+y.style_value)
        one_list = ['Normal', 'List Paragraph', 'Heading 1', 'Heading 2', 'Heading 3', 'Heading 4', 'Heading 5', 'Heading 6', 'Title', 'Subtitle']
        if len(y.yiwen_style) > 0 and y.yiwen_style in one_list:
            p = document.add_paragraph(y.yiwen_wait_over, style=y.yiwen_style)
            p.alignment = 3
            # p.alignment = alignment

    path = "static/work/yiwen_doc/" + file.file_name
    # 把生成的word文档路径存到数据库
    sqL_oath_save = models.file_information.objects.get(id = file_id)
    sqL_oath_save.word_path = path
    sqL_oath_save.save()
    document.save(path)
    return path, file.file_name


# 缓冲流下载文件方法
def readFile(filename, chunk_size=512):
    with open(filename, 'rb') as f:
        while True:
            c = f.read(chunk_size)
            if c:
                yield c
            else:
                break


# 导出word
@login_required
# @require_http_methods(["POST"])
def downloads(request, file_id):
    file = models.file_information.objects.get(pk = file_id)
    print(file.file_name)
    # 获取当前的用户
    user = request.user
    # 获取当前ID的用户
    id_user = file.file_user
    # 判断是否用户是否为一人
    if user == id_user:
        path, file_name = word_ok(file_id)
        print(path)
        print(file_name)
        response = StreamingHttpResponse(readFile(path))
        response['Content-Type'] = 'application/octet-stream'
        response['Content-Disposition'] = 'attachment;filename="download.docx"'
        # 把状态改为已完成
        file = models.file_information.objects.get(pk = file_id)
        file.file_status = 0
        file.save()
        return response
    else:
        return render(request, 'work/update.html', {})


# 删除文件
@login_required
# @require_http_methods(["POST"])
def del_file(request, file_id):
    file = models.file_information.objects.get(pk = file_id)
    print(file.file_name)
    # 获取当前的用户
    user = request.user
    # 获取当前ID的用户
    id_user = file.file_user
    # 判断是否用户是否为一人
    if user == id_user:
        file = models.file_information.objects.get(pk = file_id)
        file.file_status = 2
        file.save()
        return redirect('/work/')
    else:
        return render(request, 'work/work_error.html', {})

import json
from django.http import HttpResponse
# 单行/全部提交译文
@csrf_exempt
@login_required
@require_http_methods(["POST"])
def change_yiwen(request, id, yiwen):
    print(yiwen, id)
    # 查找译文表，把提交的译文存入到译文列和待修改列
    p = models.yiwen.objects.get(gl_id = id)
    p.yiwen = yiwen
    p.yiwen_wait_over = yiwen
    p.save()
    # 查找原文表，得出原文的长度
    yuanwen = models.yuanwen.objects.get(pk=id)
    yuanwen_len = len(yuanwen.yuanwen)
    print("原文长：", yuanwen_len)
    print(yuanwen.file.id)
    # 查找文件信息表，把提交来的译文的原文长度存到数据库中 并将是否可修改改为1（不可修改）
    file = models.file_information.objects.get(pk=yuanwen.file.id)
    if yuanwen.check_changeed != 1:
        yuanwen.check_changeed = 1
        file.numing += yuanwen_len
        file.paraing += 1
        jindu = int((yuanwen_len+file.numing)/file.all_num*100)
        if jindu >= 100:
            jindu = 100
        file.jindu = jindu
        file.save()
        yuanwen.save()
    resp = {'numing': file.numing, 'paraing': file.paraing, 'jindu':file.jindu, "all_num":file.all_num, "all_para":file.all_para}
    return HttpResponse(json.dumps(resp), content_type="application/json")


# 全部保存译文
@login_required
@require_http_methods(["POST"])
def all_save_yiwen(request, y_id, yiwen):
    try:
        print(y_id, yiwen)
        p = models.yiwen.objects.get(gl_id=y_id)
        print(p)
        if request.method == 'POST':
            print(yiwen)
            p.yiwen_wait_over = yiwen
            p.save()
            return JsonResponse({"msg": "全部保存成功", "success": True})
    except:
        return JsonResponse({"msg": "全部保存失败", "success": False})


# 搜索原文
@login_required

work/templates/work/file_info.html
{% extends 'base.html' %}
{% block title_name %}
工作主页
{% endblock %}
{%  block nav %}
<!-- 导航开始 -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!--<a class="navbar-brand" href="/work/">人机共译系统</a>-->
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/work/">主页 <span class="sr-only">(current)</span></a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if user.username %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">{{request.user}} <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="/users/{{request.user.id}}/user_info/">个人主页</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="/users/user_logout/">安全退出</a></li>
                    </ul>
                </li>

                {% else %}
                <li><a href="{% url 'users:register' %}">注册</a></li>
                <li><a href="{% url 'users:sign_in' %}">登录</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<!-- 导航结束 -->
{% endblock %}
{% block main %}
{% load static %}
<link rel="stylesheet" href="{% static 'work/css/app/index.css' %}">
<link rel="stylesheet" href="{% static 'work/css/lib/wui.css' %}">
<script src="{% static 'work/js/lib/jquery-1.11.2.min.js' %}"></script>
<script src="{% static 'work/js/lib/angular.min.js' %}"></script>
<script src="{% static 'work/js/lib/wui-date.js' %}"></script>

<main style="background-color: #f1f1f1;">
    <div class="box">
        <div class="top"></div>
        <form enctype="multipart/form-data" method="post" action="/work/file_info/">
            {% csrf_token %}
            <!--<h3>文件名称：{{msg}}</h3>-->
            <table class="table table-bordered table-hover table-responsive">
                <tr>
                    <th>文件名称:</th>
                    <td>
                        <input type="text" value="{{msg}}" name="name" class="form-control" id="exampleInputEmail1">
                    </td>
                </tr>
                <tr>
                    <th>源语言：</th>
                    <td>
                        <!--<input type="text" readonly="readonly">-->
                        <select name="yuan" id="" required="required" class="form-control">
                            <option value="0">选择源语言</option>
                            <option value="1">中文</option>
                            <option value="2">英文</option>
                        </select>
                    </td>
                </tr>
                 <tr>
                    <th>目标语言：</th>
                    <td>
                        <!--<input type="text" readonly="readonly">-->
                        <select name="mubiao" id="" required="required" class="form-control">
                            <option value="0">选择目标语言</option>
                            <option value="1">中文</option>
                            <option value="2">英文</option>
                        </select>
                    </td>
                </tr>
                 <tr>
                    <th>截至日期：</th>
                    <td>
                        <input type="text" name="over_time" id="ttime" hidden="hidden">
                        <wui-date
                            format="yyyy-mm-dd hh:mm"
                            placeholder="请选择或输入日期"
                            id="date3"
                            btns="{'ok':'确定','now':'此刻'}"
                            ng-model="date3"
                        >
                        </wui-date>
                    </td>
                </tr>
                <input type="text" value="{{id}}" name="id" hidden>
                <tr>
                    <th>项目备注：</th>
                    <td>
                        <textarea name="info" class="form-control" rows="3"></textarea>
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <input class="btn btn-info" type="submit" value="下一步">
                    </td>
                </tr>
            </table>   
        </form>
    </div>
    <script>
        var app = angular.module('app',["wui.date"]);

        $("#date3").click(function () {
            // alert("11")
            console.log(this.text)
        })
    </script>
</main>
{% endblock %}

work/templates/work/serch.html
{% extends 'base.html' %}
{% block title_name %}
搜索
{% endblock %}
{%  block nav %}
<!-- 导航开始 -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!--<a class="navbar-brand" href="/work/">人机共译系统</a>-->
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/work/">主页 <span class="sr-only">(current)</span></a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if user.username %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">{{request.user}} <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="/users/{{request.user.id}}/user_info/">个人主页</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="/users/user_logout/">安全退出</a></li>
                    </ul>
                </li>

                {% else %}
                <li><a href="{% url 'users:register' %}">注册</a></li>
                <li><a href="{% url 'users:sign_in' %}">登录</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<!-- 导航结束 -->
{% endblock %}
{% block main %}
{% load static %}
<!--<link rel="stylesheet" href="{% static 'work/css/app/index.css' %}">-->
<link rel="stylesheet" href="{% static 'work/css/app/work.css' %}">

<main style="background-color: #fff;">
    <div class="box">
        <div class="top"></div>
        <div class="serch">
            <!-- <form action="/work/serch_yuanwen/{{file_id}}/" method="post">
                {% csrf_token %}
                <input type="text" placeholder="搜索原文" id="s1" name="yuanwen_keyword">
            </form>
            <form action="/work/serch_yiwen/{{file_id}}/" method="post">
                {% csrf_token %}
                <input type="text" placeholder="搜索译文" id="s2" name="yiwen_keyword">
            </form>
            <button class="btn btn-default" style="margin-left: 15%;">全部保存</button>
            <button class="btn btn-default" style="margin-left: 3%;" onclick="window.location.href='/work/{{file_id}}/downloads/'">导出</button> -->
            <a href="/work/{{file_id}}/work">返回上一页重载页面，本地刷新</a>
        </div>
        <div class="box" id="content">
            <table class="table table-striped table-bordered table-hover table-responsive">
                <tr class="active">
                    <th>句段</th>
                    <th class="yuanwen">原文栏</th>
                    <th>状态</th>
                    <th class="yiwen">译文栏</th>
                    <th>MT选择</th>
                    <th>保存</th>
                </tr>
                {% for f,y in wenjian %}
                <tr>
                <form action="/work/{{y.id}}/change_yiwen/" method="post">
                    {% csrf_token %}
                    <td>{{forloop.counter}}</td>
                    <td id="f{{forloop.counter}}"class="yuanwen" style="text-align: left;">{{f.yuanwen}}</td>
                    <td>√</td>
                    <td id="y{{forloop.counter}}" class="yiwen" style="text-align: left;">
                    <input type="text" value="{{y.id}}" name="yiwen_id" hidden>
                    <!--<textarea name="yiwen" id="yiwen" cols="30" rows="10" hidden>{{y.yiwen}}</textarea>-->
                    <input type="text" name="yiwen" id="yiwen{{y.id}}" value="{{y.yiwen_wait_over}}" hidden>
                    <div class="textarea" id="yiwen_show{{y.id}}" contenteditable="true" onblur="console.log(document.getElementById('yiwen{{y.id}}').value=this.innerText);">{{y.yiwen_wait_over}}</div>
                        <!--onblur="document.getElementById('yiwen_show{{y.id}}').html==document.getElementById('yiwen{{y.id}}').value; "-->
                        <!--onblur="this.innerText-->
                    </td>
                    <td>
                        <a href="javascript:void(0);" id="bd{{forloop.counter}}">百度翻译</a>
                        <a href="javascript:void(0);" id="g{{forloop.counter}}">搜狗翻译</a>
                    </td>
                    <td><input type="submit" value="保存" id></td>
                </form>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</main>
{% endblock %}

work/templates/work/work_error.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>错误 错误</title>
</head>
<body>
	<h1>请到您本人下de项目(手动再见)</h1>
	<a href="/work/">返回您的首页</a>
</body>
</html>