second_Edition/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 用户
    url(r'^users/', include('users.urls', namespace='users')),
    # 首页（公共）
    url(r'^', include('commons.urls', namespace='commons')),
    # 首页（公共）
    url(r'^work/', include('work.urls', namespace='work')),
]

users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # 登录页面
    url(r'^$', views.user_login, name='sign_in'),
    url(r'^login/$', views.user_login, name='sign_in'),
    # 注册页面
    url(r'^register/$', views.register, name='register'),
    # 验证码
    url(r'^code/$', views.code, name='code'),
    # 验证邮箱是否可用
    url(r'^(.*)/checkemail/$', views.checkemail, name='checkemail'),
    # 验证昵称
    url(r'^(.*)/checkusername/$', views.checkusername, name='checkusername'),
    # 注册后提示
    url(r'^tips/$', views.tips, name='tips'),
    # 邮箱验证
    url(r'^email_verification/(?P<token>.*)$', views.email_verification, name='email_verification'),
    # 验证码验证
    url(r'^(\w+)/checkcode/$', views.checkcode, name='checkcode'),
    # 退出登录
    url(r'^user_logout/$', views.user_logout, name='user_logout'),
    # 个人主页
    url(r'^(\d+)/user_info/$', views.user_info, name='user_info'),
    # ajax验证旧密码
    url(r'^(\w+)/check_password/$', views.check_password, name='check_password'),
    # 修改密码
    url(r'change_pwd/', views.change_pwd, name='change_pwd'),
    # 修改昵称
    url(r'(\w+)/change_username/', views.change_username, name='change_username'),
    # 修改邮箱
    url(r'change_email/', views.change_email, name='change_email'),
]

work/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index/$', views.index, name='index'),
    url(r'^file_update/$', views.file_update, name='file_update'),
    url(r'^update/$', views.update, name='update'),
    url(r'^file_info/$', views.file_info, name='file_info'),
    url(r'^trans_type/$', views.trans_type, name='trans_type'),
    # url(r'^(\d+)/(\d+)/(\d+)/work_wait/$', views.work_wait, name='work_wait'),
    url(r'^work_wait/$', views.work_wait, name='work_wait'),
    # 工作区
    # 中文编译界面
    url(r'^(\d+)/work/$', views.work, name='work'),
    # 英文编译界面
    url(r'^(\d+)/enwork/$', views.enwork, name='enwork'),
    # 下载/导出  word
    url(r'^(\d+)/downloads/$', views.downloads, name='downloads'),
    # 删除文档项目
    url(r'^(\d+)/del_file/$', views.del_file, name='del_file'),
    # 单行/全部修改译文
    url(r'^(\d+)/([\s\S]*)/change_yiwen/$', views.change_yiwen, name='change_yiwen'),
    # url(r'^(\d+)/enchange_yiwen/$', views.enchange_yiwen, name='enchange_yiwen'),
    # 生成word
    # url(r'^(\d+)/word_ok/$', views.word_ok, name='word_ok'),
    # 搜索原文
    url(r'serch_yuanwen/(\d+)/$', views.serch_yuanwen, name="serch_yuanwen"),
    url(r'serch_yiwen/(\d+)/$', views.serch_yiwen, name="serch_yiwen"),
    # 中文
    url(r'bdjson/([\s\S]*)/(\d+)/$', views.bdjson, name="bdjson"),
    url(r'sgjson/([\s\S]*)/(\d+)/$', views.sgjson, name="sgjson"),
    # 英文
    url(r'en_baidu/([\s\S]*)/(\d+)/$', views.en_baidu, name="en_baidu"),
    url(r'ensgjson/([\s\S]*)/(\d+)/$', views.ensgjson, name="ensgjson"),
    # url(r'all_change_yiwen/(\d+)/([\s\S]*)/$', views.all_change_yiwen, name="all_change_yiwen"),
    url(r'all_save_yiwen/(\d+)/([\s\S]*)/$', views.all_save_yiwen, name="all_save_yiwen"),
    url(r'change_befor/(\d+)/$', views.change_befor, name="change_befor"),
    url(r'change_old/(\d+)/$', views.change_old, name="change_old"),
    url(r'change_content/([\s\S]*)/(\d+)/$', views.change_content, name="change_content"),
    url(r'en_content_change/([\s\S]*)/(\d+)/$', views.en_content_change, name="en_content_change"),
    url(r'yuanwen_check/(\d+)/$', views.yuanwen_check, name="yuanwen_check"),
    url(r'yiwen_check/(\d+)/$', views.yiwen_check, name="yiwen_check"),
    # 中文编译
    url(r'zh_rs/(\d+)/$', views.zh_rs, name="zh_rs"),
    url(r'en_read_save/(\d+)/$', views.en_read_save, name="en_read_save"),
]

users/models.py
from django.db import models
# 导入内置的用户表
from django.contrib.auth.models import User


# 创建用户的扩展信息表
class users_more_info(models.Model):
    id = models.AutoField(primary_key=True)
    phone = models.CharField(max_length=11, null=True, verbose_name='手机号码')
    # 绑定
    user = models.OneToOneField(User, on_delete=models.CASCADE)

users/views.py
from django.shortcuts import render, HttpResponse
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.shortcuts import redirect   # 路由重定向
from django.contrib.auth.models import User     # 内置用户
from django.contrib.auth import authenticate, login, logout     # 内置的用户认证
from django.contrib.auth.decorators import login_required       # 登录检查
from itsdangerous import TimedJSONWebSignatureSerializer
from . import models
from . import tools
from io import BytesIO  # 在内存中读写bytes
from . import zsend_email
import os
os.environ['DJANGO_SETTINGS_MODULE'] = 'second_Edition.settings'


# 登录
def user_login(request):
    if request.method == 'GET':
        try:
            next_url = request.GET['next']
        except:
            next_url = "/work/"

        print(next_url)
        return render(request, 'users/sign_in.html', {"next_url": next_url})
        # return render(request, 'users/sign_in.html', {})
    if request.method == 'POST':
        username = request.POST['username'].strip()
        password = request.POST['password'].strip()
        islong = request.POST.get("islong", "no")
        next_url = request.POST.get("next", "/work/")
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                request.session["LoginUser"] = user
                if islong == "on":
                    request.session.set_expiry(3600 * 24 * 7)
                elif islong == "":
                    request.session.set_expiry(0)
                return redirect(next_url)

            else:
                return render(request, 'users/sign_in.html', {"msg": "未激活"})
        else:
            return render(request, 'users/sign_in.html', {"msg": "账户、密码错误或账户未激活"})


# 注册
def register(request):
    if request.method == 'GET':
        return render(request, 'users/register.html', {})
    if request.method == 'POST':
        username = request.POST['username'].strip()
        email = request.POST['email'].strip()
        password = request.POST['password'].strip()
        querenpassword = request.POST['confirm_password'].strip()
        code = request.POST['code']
        # 后台验证
        if code.upper() != request.session['code'].upper():
            return render(request, 'users/register.html', {"msg": "验证码不正确，请重新注册"})
        if len(password) < 6:
            return render(request, 'users/register.html', {"msg": "密码长度不足6位，请重新注册"})
        if password != querenpassword:
            return render(request, 'users/register.html', {"msg": "两次输入密码不一致，请重新注册"})
        try:
            # 用户名验证
            User.objects.get(email=email)
            return render(request, 'users/register.html', {"msg": "用户名已存在，请重新注册"})
        except:
            try:
                # create_user辅助函数创建用户
                user = User.objects.create_user(password=password, username=username, email=email, is_active=0)
                usera = models.users_more_info(user=user)
                user.save()
                usera.save()
                # 发送验证邮件
                print("发送邮件")
                zsend_email.mail(user.email, user.id)
                # return render(request, "user/tiaozhuan.html", {"msg": "恭喜注册成功，请登录"})
                return redirect('/users/tips')
            except:
                return render(request, "users/register.html", {"msg": "注册失败，请重新注册"})


# 验证码 函数
def code(request):
    img, code = tools.create_code()
    # 首先需要将code 保存到session 中
    request.session['code'] = code
    # 返会图片
    file = BytesIO()
    img.save(file, 'PNG')

    return HttpResponse(file.getvalue(), "image/png")


# ajax验证邮箱
def checkemail(request, email):
    try:
        User.objects.get(email=email)
        return JsonResponse({"msg": "此邮箱已注册，请重新输入", "success": False})
    except:
        return JsonResponse({"msg": "邮箱可用，请继续输入", "success": True})


# ajax验证邮箱
def checkusername(request, username):
    try:
        User.objects.get(username=username)
        return JsonResponse({"msg": "此昵称已注册，请重新输入", "success": False})
    except:
        return JsonResponse({"msg": "昵称可用，请继续输入", "success": True})


# 邮箱链接激活
def email_verification(request, token):
    SECRET_KEY = 's(do(h$i-d3rzrx7yhw@ik!cgwg+52-c#roc*3gk#wfk2y@1=2'
    s = TimedJSONWebSignatureSerializer(SECRET_KEY, expires_in=3600*64)
    try:
        data = s.loads(token)
        id = data["confirm"]
        print(id)
        user = User.objects.get(pk=id)
        user.is_active = 1
        user.save()
        return redirect('/users/')
    # 验证失败，会抛出异常
    except:
        print("over")
        return HttpResponse('激活链接已过期')


    # 注册之后跳转提示界面
def tips(request):
    return render(request, 'users/tips.html', {})


# ajax验证验证码
def checkcode(request, code):
    s_code = request.session['code']
    if s_code.upper() != code.upper():
        return JsonResponse({"msg": "验证码错误，请重新填写", "success": False})
    else:
        return JsonResponse({"msg": "验证码正确，请注册", "success": True})


# 退出登录
@login_required
def user_logout(request):
    logout(request)
    return redirect('/')


# 个人主页
@login_required
def user_info(request, id):
    user = models.users_more_info.objects.get(user=id)
    return render(request, 'users/user_info.html', {'user_info':user_info})


# 修改密码
@login_required
def change_pwd(request):
    old_pwd = request.POST['old_pwd'].strip()
    new_pwd = request.POST['new_pwd'].strip()
    new_pwd2 = request.POST['new_pwd2'].strip()
    print(old_pwd, new_pwd, new_pwd2)

    user = User.objects.get(pk=request.user.id)
    user = authenticate(username=user.username, password=old_pwd)
    if user is None:
        return redirect(request, 'users/user_info.html', {'script': "alert", 'wrong': '输入的旧密码不正确'})
    else:
        if new_pwd != new_pwd2:
            return render(request, 'users/user_info.html', {'script': "alert", 'wrong': '两次输入的密码不相同'})
            # return HttpResponseRedirect('/users/'+str(user.id)+'/user_info?script=alert&wrong=两次输入的密码不相同')
        else:
            user.set_password(new_pwd)
            user.save()
            user_logout(request)
            return redirect('/users/')
            # except:
            #     return render(request, 'users/user_info.html', {'script': "alert", 'wrong': '修改密码失败'})


# ajax验证旧密码
@login_required
def check_password(request, old_pwd):
    u = User.objects.get(pk=request.user.id)
    print(u)
    print(u.username)
    user = authenticate(username=u.username, password=old_pwd)
    if user is None:
        return JsonResponse({"msg": "输入的旧密码不正确", "success": False})
    else:
        return JsonResponse({"msg": "", "success": True})


def change_username(request, username):
    # ajax实现修改昵称
    user = User.objects.get(pk = request.user.id)
    if len(username) != 0:
        user.username = username
        user.save()
        return JsonResponse({"msg": "", "success": True})


def change_email(request, email):
    # ajax实现修改邮箱
    pass

    # 参考验证旧密码，路由还没有配  \W+

users/templates/users/register.html
{% extends 'base.html' %}
{% block title_name %}
注册——等你很久了~
{% endblock %}


{% block main %}
{% load static %}
<link rel="stylesheet" href="{% static 'users/css/app/register.css' %}">
<script src="{% static 'js/lib/jquery.js' %}"></script>
<div class="register">
    <div class="box">
        <h2 style="margin-bottom: 20px;">用户注册</h2>
        <h5 id="msg">{{msg}}</h5>
        <form class="form-horizontal" method="post" action="/users/register/">
            {% csrf_token %}

            <div class="form-group">
                <label for="username" class="col-sm-2 control-label">昵称：</label>
                <div class="col-sm-10">
                    <input type="text" required="required" name='username' class="form-control" id="username" placeholder="请输入您的昵称">
                </div>
            </div>

            <div class="form-group">
                <label for="email" class="col-sm-2 control-label">邮箱：</label>
                <div class="col-sm-10">
                    <input type="email" required="required" name='email' class="form-control" id="email" placeholder="请输入您的邮箱">
                </div>
            </div>
            <div class="form-group">
                <label for="password" class="col-sm-2 control-label">密码：</label>
                <div class="col-sm-10">
                    <input type="password" required="required" name="password" class="form-control" id="password" placeholder="请输入密码">
                </div>
            </div>

            <div class="form-group">
                <label for="confirm_password" class="col-sm-2 control-label">确认密码：</label>
                <div class="col-sm-10">
                    <input type="password" required="required" name="confirm_password" class="form-control" id="confirm_password"
                           placeholder="请确认密码">
                </div>
            </div>

            <div class="form-group">
                <label for="yzm" class="col-md-2 control-label">验证码：</label>
                <div class="col-md-4">
                    <input type="text" autocomplete="off" id="yzm" class="form-control" placeholder="请输入验证码" name="code"
                           required="required">
                </div>
                <div class="col-md-4">
                    <a onclick="changeCode()" href="javascript:void(0)"><img id="code" src="{% url 'users:code' %}"
                                                                             alt="验证码" title="点击刷新验证码"></a>
                </div>
                <!--<div class="col-md-2">-->
                <!--<a onclick="changeCode()" href="javascript:void(0)">点击刷新验证码</a>-->
                <!--</div>-->
                <div class="col-md-2"></div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" id="sub_btn" class="btn btn-default">注册</button>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    // 刷新验证码
    function changeCode() {
        document.getElementById("code").src = "/users/code?id=" + Math.random()
    }
    // 验证邮箱
    $(function () {
        $("#email").on("blur", function () {
            email = $("#email").val()
            if (email.length > 1){
                $.ajax({
                    url: "/users/" + email + "/checkemail/",
                    method: "POST",
                    dataType: "json",
                    data: {"csrfmiddlewaretoken": "{{ csrf_token }}"},
                    success: function (data) {
                        if (data.success) {
                            // $("#sub_btn").removeAttr("disabled")
                            // $("#sub_btn").css("display","block");
                            $("#msg").html("<span style='color:green;'>" + "" + "</span>")
                            {#$("#msg").html("<span style='color:green;'>" + data.msg + "</span>")#}
                        } else {
                            // $("#uname").addClass("has-error")
                            // $("#sub_btn").attr("disabled", true)
                            $("#msg").html("<span style='color:red;font-size: 12px;line-height: 5px;'>" + data.msg + "</span>")
                        }
                    }
                })
            }else{
                $("#msg").html("<span style='color:red;font-size: 12px;line-height: 5px;'>" + "邮箱不能为空" + "</span>")
                }
        })

        // 验证用户名
        $("#username").on("blur", function () {
            username = $("#username").val()
            if (username.length > 1) {
                $.ajax({
                    url: "/users/" + username + "/checkusername/",
                    method: "POST",
                    dataType: "json",
                    data: {"csrfmiddlewaretoken": "{{ csrf_token }}"},
                    success: function (data) {
                        if (data.success) {
                            // $("#sub_btn").removeAttr("disabled")
                            // $("#sub_btn").css("display","block");
                            $("#msg").html("<span style='color:green;'>" + "" + "</span>")
                            {#$("#msg").html("<span style='color:green;'>" + data.msg + "</span>")#}
                        } else {
                            // $("#uname").addClass("has-error")
                            // $("#sub_btn").attr("disabled", true)
                            $("#msg").html("<span style='color:red;font-size: 12px;line-height: 5px;'>" + data.msg + "</span>")
                        }
                    }
                })
            }else{
                $("#msg").html("<span style='color:red;font-size: 12px;line-height: 5px;'>" + "昵称不能为空" + "</span>")
            }
        })


        // 验证密码
        $(function () {
            $("#password").on("blur", function () {
                password = $("#password").val()
                if (password.length < 6) {
                    // $("#pwb").addClass("has-error")
                    // $("#sub_btn").attr("disabled", true)
                    $("#msg").html("<span style='color:red;'>" + "密码长度不足6位" + "</span>")
                } else {
                    // $("#pwb").addClass("has-success")
                    // $("#sub_btn").removeAttr("disabled")
                    // $("#sub_btn").css("display","block");
                    $("#msg").html("<span style='color:green;'>" + "" + "</span>")
                    {#$("#msg").html("<span style='color:green;'>" + "密码合法！！请继续输入" + "</span>")#}
                }
            })
        })
        // 第二次密码验证
        $(function () {
            $("#confirm_password").on("blur", function () {
                confirm_password = $("#confirm_password").val()
                if (confirm_password != password) {
                    // $("#pwb2").addClass("has-error")
                    // $("#sub_btn").attr("disabled", true)
                    $("#msg").html("<span style='color:red;'>" + "两次密码不一致，请重新输入" + "</span>")
                } else {
                    // $("#pwb2").addClass("has-success")
                    // $("#sub_btn").removeAttr("disabled")
                    {#$("#sub_btn").css("display", "block");#}
                    $("#msg").html("<span style='color:green;'>" + "" + "</span>")
                    {#$("#msg").html("<span style='color:green;'>" + "两次密码一致,请注册" + "</span>")#}
                }
            })
        })
        // 验证验证码
        $(function () {
            $("#yzm").on("blur", function () {
                yzm = $("#yzm").val()
                $.ajax({
                    url: "/users/" + yzm + "/checkcode/",
                    method: "POST",
                    dataType: "json",
                    data: {"csrfmiddlewaretoken": "{{ csrf_token }}"},
                    success: function (data) {
                        if (data.success) {
                            // $("#sub_btn").removeAttr("disabled")
                            // $("#sub_btn").css("display","block");
                            $("#msg").html("<span style='color:green;'>" + "" + "</span>")
                            {#$("#msg").html("<span style='color:green;'>" + data.msg + "</span>")#}
                        } else {
                            // $("#uname").addClass("has-error")
                            // $("#sub_btn").attr("disabled", true)
                            {#$("#sub_btn").css("display", "none");#}
                            $("#msg").html("<span style='color:red;font-size: 12px;line-height: 5px;'>" + data.msg + "</span>")
                        }
                    }
                })
            })

        })
    })

</script>
{% endblock %}

users/templates/users/sign_in.html
{% extends 'base.html' %}
{% block title_name %}
登录——欢迎回来~
{% endblock %}


{% block main %}
{% load static %}
<link rel="stylesheet" href="{% static 'users/css/app/register.css' %}">
<script src="{% static 'js/lib/jquery.js' %}"></script>
<div class="register">
    <div class="box">
        <h2 style="margin-bottom: 20px;">用户登录</h2>
        <h5 id="msg">{{msg}}</h5>
        <form class="form-horizontal" action="/users/login/" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username" class="col-sm-2 control-label">账号：</label>
                <div class="col-sm-10">
                    <input type="text" required="required" class="form-control" id="username" name="username"
                           placeholder="请输入您的昵称">
                </div>
            </div>
            <div class="form-group">
                <label for="password" class="col-sm-2 control-label">密码：</label>
                <div class="col-sm-10">
                    <input type="password" required="required" class="form-control" id="password" name="password"
                           placeholder="请输入密码">
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="islong"> 七天免密登录
                        </label>
                    </div>
                </div>
            </div>
<input type="text" name="next" value="{{next_url}}" hidden>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default" id="sub_btn">登录</button>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    // 验证密码
    $(function () {
        $("#password").on("blur", function () {
            console.log("abc")
            password = $("#password").val()
            console.log(password.length)
            if (password.length < 6) {
                // $("#pwb").addClass("has-error")
                // $("#sub_btn").attr("disabled", true)
                $("#msg").html("<span style='color:red;'>" + "密码长度不足6位" + "</span>")
            } else {
                // $("#pwb").addClass("has-success")
                // $("#sub_btn").removeAttr("hidden")
                {#$("#sub_btn").css("display", "block");#}
                $("#msg").html("<span style='color:green;'>" + "" + "</span>")
                {#$("#msg").html("<span style='color:green;'>" + "密码合法！！请继续输入" + "</span>")#}
            }
        })
    })
</script>
{% endblock %}

users/templates/users/tips.html
{% extends 'base.html' %}
{% block title_name %}
邮箱验证 提醒~
{% endblock %}
{% block nav %}
<!-- 导航开始 -->
    <nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">人机共译系统</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/">首页 <span class="sr-only">(current)</span></a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    <!-- 导航结束 -->
{% endblock %}
{%  block main %}
<div class="container" style="min-height: 555px;text-align: center;">
    <h1 style="color: green;margin-top: 200px;font-weight: 800;font-size: 55px;">注册成功~</h1>
    <h2>需要点击邮箱的验证链接才可以继续使用哟~</h2>
    <h3>快去查看您注册邮箱的邮件吧！</h3>
</div>
{% endblock %}